### ISSUE TITLE
displayName checking erroneously triggered

### ISSUE THREAD

**Issue by gecole** [chb/ccdaScorecard#10]
This issue: The Display Names used by the structured data should match the Display Name (Preferred Name) within the Terminology

is reported even when content does not supply the optional displayName.

Agree that when a displayName is supplied that it should match the Display or Preferred Name from the terminology, but absence of the displayName attribute, since it is optional, is perfectly acceptable and should not trigger this rule checking.

**Comment by jmandel** [comment]
Thanks @gecole! I'm looking at winding down this tool now that ONC has built a C-CDA 2.1 version of it — but briefly revising my goals from 2012, the reason we check `displayName` is because the Scorecard is a prescriptive tool (i.e. its advice isn't just about determining whether a document is conformant to the official spec, where `displayName` is of course optional; the scorecard advice is about giving developers a sense of whether they're meeting best practices — and in that sense, I didn't think a missing `displayName` was "perfectly acceptable".)
